"""Departures and successors during each Congress, for notes in the rosters at the opening.
# Usage: python3 tools/congress/make_changes.py [--cache DIR]
#   Writes congress/changes.yaml from the 'Changes in membership' tables of Wikipedia's pages for the
#   87th through 93rd Congresses: the seat, who left and why (with the date), the successor and party,
#   and the date the successor was seated. Delegates are left out. Check against the Biographical
#   Directory of the Congress where a date matters.
"""
import os
import sys
import tempfile
import urllib.request

import yaml

sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', 'elections'))
import wiki  # noqa: E402

OUT = os.path.join(os.path.dirname(__file__), '..', '..', 'congress', 'changes.yaml')
ORD = {87: '87th', 88: '88th', 89: '89th', 90: '90th', 91: '91st', 92: '92nd', 93: '93rd'}


def main():
    cache = sys.argv[sys.argv.index('--cache') + 1] if '--cache' in sys.argv else tempfile.gettempdir()
    out = {}
    for c, name in ORD.items():
        p = os.path.join(cache, f'cg_{name}.txt')
        if not os.path.exists(p):
            url = f'https://en.wikipedia.org/w/index.php?title={name}_United_States_Congress&action=raw'
            req = urllib.request.Request(url, headers={'User-Agent': 'Mozilla/5.0 (bibliography)'})
            open(p, 'wb').write(urllib.request.urlopen(req, timeout=120).read())
        rows = [x for x in wiki.changes(open(p, encoding='utf-8').read()) if x['st']]
        out[c] = rows
        print(c, len(rows))
    head = ('# Generated by tools/congress/make_changes.py from Wikipedia\'s Congress pages ("Changes in membership").\n'
            '# Per Congress: ch (h|s), st, seat (district, 0 at large; Senate class), out, out_party, reason, into,\n'
            '# into_party, seated.\n')
    open(OUT, 'w', encoding='utf-8').write(head + yaml.safe_dump(out, sort_keys=False, allow_unicode=True, width=200))


if __name__ == '__main__':
    main()
