"""Write daybook/recordings/<YYYY-MM>.yaml: the White House recordings of the calendar's span, from the catalogue of
the Miller Center's Presidential Recordings Digital Edition (PRDE, University of Virginia Press).

    python3 tools/daybook/make_recordings.py            (needs the network; the build does not)

What is taken: the catalogue only, as PRDE's public search lists it: the recording's title, date and time, place,
length, the persons PRDE lists as speakers, the tape cite (the LBJ Library's conversation number, "WH6407-11-4288";
for Kennedy, the tape), the Edition's volume, and the address of its page. Not taken: the transcripts and the editors'
introductions, which are the Edition's text and behind its subscription.

STYLE (rendered by tools/bib/daybook.py):
 1. One row a recording: key 'prde:<id>', src 'prde', date, time (HH:MM; none where PRDE gives none or a placeholder,
    00:00 or 23:59:59), title (PRDE's, its closing "on 21 July 1964" dropped: the day is the heading), speakers (as
    PRDE writes them, "Kennedy, Robert F."; unidentified speakers, operators and secretaries left out), place,
    duration, tape (Kennedy's: the tape alone, "Tape 5A"), vol, url.
 2. PRDE's daily introductions (editorial essays, not recordings) are left out.
 3. Within a day, by time; recordings without a time last, in PRDE's order.
"""
import json
import os
import re
import sys
import time
import urllib.parse
import urllib.request

import yaml

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
OUT = os.path.join(ROOT, "daybook", "recordings")
FROM, TO = "1961-01-20", "1966-01-10"
API = "https://prde.upress.virginia.edu/v1/search?"
PAGE = "https://prde.upress.virginia.edu/conversations/"
NOT_SPEAKERS = re.compile(r"^(Unidentified|Speaker, Unidentified|White House Operator|Operator|Secretary|"
                          r"White House Secretary|Unknown|——)", re.I)


def fetch(start, n=100):
    q = f"date GE {FROM} AND date LE {TO}"
    u = API + urllib.parse.urlencode({"q": q, "format": "json", "options": "all", "start": start, "pageLength": n})
    req = urllib.request.Request(u, headers={"User-Agent": "bib-daybook (https://impending2223.github.io/bib/)"})
    for attempt in range(4):
        try:
            return json.load(urllib.request.urlopen(req, timeout=90))
        except Exception:
            time.sleep(2 ** (attempt + 1))
    raise SystemExit(f"PRDE did not answer for start={start}")


def row(r):
    m = {}
    for x in r.get("metadata", []):
        for k, v in x.items():
            if k != "metadata-type":
                m.setdefault(k.split("}")[-1], []).append(v)
    one = lambda k: (m.get(k) or [None])[0]
    title = (one("displayTitle") or "").strip()
    if not title or re.match(r"^(Daily Introduction|Introduction to)", title, re.I):
        return None
    date = one("date")
    if not date or not (FROM <= date <= TO):
        return None
    t = (one("dateTime") or "")[11:16]
    if t in ("", "00:00", "23:59"):
        t = None
    title = re.sub(r"\s+on \d{1,2} [A-Z][a-z]+ \d{4}\s*$", "", title)
    speakers = []
    for s in m.get("speaker") or []:
        s = s.strip()
        if s and not NOT_SPEAKERS.match(s) and s not in speakers:
            speakers.append(s)
    uid = r["uri"].rsplit(".", 1)[0]
    out = {"key": f"prde:{uid}", "src": "prde", "date": date}
    if t:
        out["time"] = t
    out["title"] = title
    out["speakers"] = speakers
    for k, name in (("place", "place"), ("duration", "duration"), ("sourceTitle", "tape"), ("volume", "vol")):
        v = one(k)
        if v and v not in ("Unspecified", "None"):
            out[name] = v.strip()
    if out.get("tape"):                  # 'Tape 5A, John F. Kennedy Library, President's Office Files, ...': the tape
        out["tape"] = re.sub(r",\s*John F\. Kennedy Library\b.*$", "", out["tape"]).strip()
    out["url"] = PAGE + uid
    return out


def main():
    rows, start = [], 1
    while True:
        d = fetch(start)
        rows += [x for x in (row(r) for r in d.get("results", [])) if x]
        start += 100
        print(f"{min(start - 1, d['total'])}/{d['total']}", file=sys.stderr)
        if start > d["total"]:
            break
        time.sleep(1)
    seen, by_month = set(), {}
    for x in rows:
        if x["key"] in seen:
            continue
        seen.add(x["key"])
        by_month.setdefault(x["date"][:7], []).append(x)
    os.makedirs(OUT, exist_ok=True)
    head = ("# Generated by tools/daybook/make_recordings.py from PRDE's catalogue. Edit the script, not this file.\n"
            "# One row a recording: key, src (prde), date, time, title, speakers, place, duration, tape, vol, url.\n")
    for mo, xs in sorted(by_month.items()):
        xs.sort(key=lambda x: (x["date"], x.get("time") or "99"))
        with open(os.path.join(OUT, f"{mo}.yaml"), "w", encoding="utf-8") as f:
            f.write(head)
            yaml.safe_dump({"month": mo, "docs": xs}, f, allow_unicode=True, sort_keys=False, width=1000)
    print(f"{len(seen)} recordings in {len(by_month)} months", file=sys.stderr)


if __name__ == "__main__":
    main()
