"""Write daybook/recordings/millercenter.yaml: the White House recordings of the calendar's span that the Miller
Center's "Secret White House Tapes" (millercenter.org, Research the Tapes) gives free: a page and the audio for each.

    python3 tools/daybook/make_millercenter.py          (needs the network; the build does not)

Read from the site's public JSON:API (node--presidential_recording), filtered by date: the title, date, time, tape,
citation number (the LBJ Library's conversation number), the page's address and the audio file's. The Library's
summaries and the site's transcripts, where it has any, are not taken. A recording PRDE catalogues (make_recordings.py)
is the same recording where the tape and the citation number agree (Johnson: PRDE's "WH6407-11-4288" is tape WH6407.11,
citation 4288; Kennedy: the tape and the conversation's number); tools/bib/daybook.py links the free page in its place.

STYLE (rendered by tools/bib/daybook.py):
 1. One row a recording: key 'mc:<nid>', date, time (HH:MM, as the site gives it, Eastern), title (the site's,
    its closing ", July 1, 1964" dropped), tape, cite, president (K or J), url, audio.
 2. Recordings the site marks without audio are left out.
"""
import json
import os
import re
import sys
import time
import urllib.parse
import urllib.request

import yaml

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
OUT = os.path.join(ROOT, "daybook", "recordings", "millercenter.yaml")
FROM, TO = "1961-01-20", "1966-01-10"
API = "https://millercenter.org/jsonapi/node/presidential_recording"
SITE = "https://millercenter.org"
FIELDS = ("drupal_internal__nid,title,path,field_date,field_time,field_tape,field_citation_number,field_audio_url,field_audio_valid,"
          "field_lbj")


def fetch(url):
    req = urllib.request.Request(url, headers={"User-Agent": "bib-daybook (https://impending2223.github.io/bib/)",
                                               "Accept": "application/vnd.api+json"})
    for attempt in range(5):
        try:
            return json.load(urllib.request.urlopen(req, timeout=120))
        except Exception as ex:
            print(f"retry {attempt + 1}: {ex}", file=sys.stderr)
            time.sleep(2 ** (attempt + 1))
    raise SystemExit(f"the Miller Center did not answer: {url}")


def first_url():
    q = {
        "filter[a][condition][path]": "field_date", "filter[a][condition][operator]": ">=",
        "filter[a][condition][value]": FROM,
        "filter[b][condition][path]": "field_date", "filter[b][condition][operator]": "<=",
        "filter[b][condition][value]": TO,
        "fields[node--presidential_recording]": FIELDS,
        "sort": "field_date,field_time,drupal_internal__nid", "page[limit]": "50",
    }
    return API + "?" + urllib.parse.urlencode(q)


def row(d):
    a = d["attributes"]
    if not a.get("field_audio_url") or a.get("field_audio_valid") is False:
        return None
    date = (a.get("field_date") or "")[:10]
    if not (FROM <= date <= TO):
        return None
    title = re.sub(r",\s+[A-Z][a-z]+\.? \d{1,2}, \d{4}\s*$", "", (a.get("title") or "").strip())
    out = {"key": f"mc:{d['attributes'].get('drupal_internal__nid') or d['id']}", "date": date}
    t = (a.get("field_time") or "")[11:16]
    if t and t not in ("00:00",):
        out["time"] = t
    out["title"] = title
    if a.get("field_tape"):
        out["tape"] = str(a["field_tape"]).strip()
    if a.get("field_citation_number") not in (None, ""):
        out["cite"] = str(a["field_citation_number"]).strip()
    out["president"] = "J" if a.get("field_lbj") else "K"
    m = re.search(r"/jfk_(\d+)([A-Za-z]?)_(\d+)\.mp3$", a["field_audio_url"])
    if m and "cite" not in out:          # Kennedy's: the tape and the item, from the audio file (jfk_001_2: tape 1, item 2)
        out["item"] = m.group(3)
    out["url"] = SITE + a["path"]["alias"] if (a.get("path") or {}).get("alias") else None
    out["audio"] = a["field_audio_url"]
    return out


def main():
    rows, url, n = [], first_url(), 0
    while url:
        d = fetch(url)
        rows += [x for x in (row(r) for r in d.get("data", [])) if x and x["url"]]
        n += len(d.get("data", []))
        print(f"{n} read, {len(rows)} kept", file=sys.stderr)
        url = ((d.get("links") or {}).get("next") or {}).get("href")
        time.sleep(0.5)
    seen, out = set(), []
    for x in rows:
        if x["key"] not in seen:
            seen.add(x["key"])
            out.append(x)
    out.sort(key=lambda x: (x["date"], x.get("time") or "99", x.get("tape") or "", x.get("cite") or ""))
    head = ("# Generated by tools/daybook/make_millercenter.py from the Miller Center's Secret White House Tapes.\n"
            "# Edit the script, not this file. One row a recording: key, date, time, title, tape, cite, president, url,\n"
            "# audio.\n")
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(head)
        yaml.safe_dump({"docs": out}, f, allow_unicode=True, sort_keys=False, width=1000)
    print(f"{len(out)} recordings", file=sys.stderr)


if __name__ == "__main__":
    main()
