"""Gallup's presidential approval for the calendar's monthly tables: each reading as released, beside the series today.
# Usage: python3 tools/indicators/make_polls.py
#   Rewrites indicators/approval.yaml for the calendar's span (FROM..TO). Needs the network; the build does not.
#
#   As released ("first", with "published" and "page"): sources/gallup-approval.yaml, read by hand from The Gallup
#   Poll: Public Opinion, 1935-1971, III (1972): field dates, approve, disapprove, no opinion, and approval among
#   Democrats, independents and Republicans where the release gives it.
#   Today ("today"): the American Presidency Project's tables of each President's job approval, "adapted from the
#   Gallup Poll and compiled by Gerhard Peters". A reading is matched by its field dates; where the two end the
#   fieldwork a day apart, one reading, the release's dates kept ("today_to": the series' last day). Readings the
#   series holds and Gallup did not release at the time have no "first". Filed by the month the fieldwork ended.
#   The race for 1964 and the issue polls are calendar entries (thread opinion), not rows here.
"""
import datetime, html, os, re, urllib.request
import yaml

FROM, TO = '1961-01-20', '1964-01-07'
OUT = os.path.join(os.path.dirname(__file__), '..', '..', 'indicators')
UA = {'User-Agent': 'bib-calendar/1.0 (research; github.com/impending2223/bib)'}
APP = 'https://www.presidency.ucsb.edu/statistics/data/'


def get(url):
    with urllib.request.urlopen(urllib.request.Request(url, headers=UA), timeout=90) as r:
        return r.read().decode('utf-8', 'replace')


def iso(d):
    m, dd, y = d.split('/')
    return f'{int(y):04d}-{int(m):02d}-{int(dd):02d}'


def approval():
    rows = []
    for slug, who in (('john-f-kennedy-public-approval', 'Kennedy'), ('lyndon-b-johnson-public-approval', 'Johnson')):
        t = get(APP + slug)
        for tr in re.findall(r'<tr[^>]*>(.*?)</tr>', t, re.S):
            c = [html.unescape(re.sub(r'<[^>]+>', '', x)).strip() for x in re.findall(r'<t[dh][^>]*>(.*?)</t[dh]>', tr, re.S)]
            if len(c) < 9 or not re.match(r'\d{1,2}/\d{1,2}/\d{4}$', c[0]):
                continue
            a, b = iso(c[0]), iso(c[1])
            if not (FROM <= b <= TO):
                continue
            n = lambda x: int(x) if x.isdigit() else None
            rows.append({'p': b[:7], 'from': a, 'to': b, 'president': who, 'approve': n(c[2]), 'disapprove': n(c[3]),
                         'unsure': n(c[4]), 'dem': n(c[6]), 'ind': n(c[7]), 'rep': n(c[8])})
    rows.sort(key=lambda r: r['to'])
    # the readings as Gallup published them (sources/gallup-approval.yaml, kept by hand from the printed volume),
    # beside the series as compiled today: one row a reading, matched by field dates
    book = yaml.safe_load(open(os.path.join(OUT, '..', 'sources', 'gallup-approval.yaml'), encoding='utf-8')) or []
    keys = ('approve', 'disapprove', 'unsure', 'dem', 'ind', 'rep')
    merged = {}
    for r in rows:
        merged[(r['from'], r['to'])] = {'p': r['p'], 'from': r['from'], 'to': r['to'], 'president': r['president'],
                                        'today': {k: r[k] for k in keys if r.get(k) is not None}}
    for b in book:
        k = (str(b['from']), str(b['to']))
        near = [x for x in merged if x[0] == k[0] and 'first' not in merged[x] and abs(
            (datetime.date.fromisoformat(x[1]) - datetime.date.fromisoformat(k[1])).days) <= 1]
        if k not in merged and near:      # the series today ends the fieldwork a day apart: one reading
            m = merged.pop(near[0])
            m.update({'p': k[1][:7], 'to': k[1], 'today_to': near[0][1]})
            merged[k] = m
        m = merged.setdefault(k, {'p': k[1][:7], 'from': k[0], 'to': k[1], 'president': b['president']})
        m.update({'published': str(b['published']), 'page': b['page'],
                  'first': {x: b.get(y) for x, y in (('approve', 'approve'), ('disapprove', 'disapprove'),
                            ('unsure', 'no_opinion'), ('dem', 'dem'), ('ind', 'ind'), ('rep', 'rep')) if b.get(y) is not None}})
        if b.get('note'):
            m['note'] = b['note']
    rows = sorted(merged.values(), key=lambda r: r['to'])
    return {'id': 'approval', 'name': 'Approval', 'kind': 'poll', 'freq': 'poll',
            'then': {'label': 'Gallup: "Do you approve or disapprove of the way [the President] is handling his job as President?"',
                     'source': 'The Gallup Poll: Public Opinion, 1935–1971, vol. III (1972), by page (sources/gallup-approval.yaml)'},
            'now': {'label': 'Gallup\'s series as compiled today', 'source': 'American Presidency Project, Presidential Job Approval (Gallup, compiled by Gerhard Peters)',
                    'url': APP + 'presidential-job-approval'},
            'rows': rows}


def write(d):
    head = ('# Generated by tools/indicators/make_polls.py. Edit the script, not this file.\n')
    path = os.path.join(OUT, d['id'] + '.yaml')
    open(path, 'w', encoding='utf-8').write(head + yaml.safe_dump(d, sort_keys=False, allow_unicode=True, width=200,
                                                                default_flow_style=None))
    print('wrote', path, len(d['rows']))


if __name__ == '__main__':
    write(approval())                    # the race and the issues are calendar entries (thread opinion), not rows
